import React, { useState, useEffect } from "react";
import StyledHeader from "./StyledHeader";
import ProfileDropDown from "./ProfileDropDown";
import Box from "@mui/material/Box";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import {
  StyledSectionTitle,
  StyledList,
  StyledAnchor,
  StyledListElement,
  StyledTitle,
  StyledNav,
} from "./StyledHeader";
import Image from "next/image";
import Head from "next/head";
import style from "./header.module.css";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";
interface Props {
  handleDrawer?: () => void;
}

export default function Header({ handleDrawer }: Props) {
  const [color, setColor] = useState(false);
  const { data: session, status } = useSession();

  const changeColor = () => {
    if (window.scrollY >= 90) {
      setColor(true);
    } else {
      setColor(false);
    }
  };

  function logoutHandler() {
    signOut();
  }

  useEffect(() => {
    // window is accessible here.
    window.addEventListener("scroll", changeColor);
  }, []);

  return (
    <>
      <Head>
        <title>Prode Qatar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/futbol4.ico" />
      </Head>
      <div className={color ? style.headerSolid : style.headerTransparent}>
        <StyledNav>
          <StyledTitle>Prode Trinche</StyledTitle>
          {/* <div style={{ display: "flex" }}> */}
          <StyledList>
            {!session && (
              <>
                <StyledListElement>
                  <Link href="/">
                    <StyledAnchor>Una Seccion</StyledAnchor>
                  </Link>
                </StyledListElement>
                <StyledListElement>
                  <Link href="/">
                    <StyledAnchor>Otra Seccion</StyledAnchor>
                  </Link>
                </StyledListElement>
                <StyledListElement>
                  <Link href="/">
                    <StyledAnchor>Otra Seccion</StyledAnchor>
                  </Link>
                </StyledListElement>
              </>
            )}
            {session && (
              <>
                <li>
                  <Link href="/">Login</Link>
                </li>
                <StyledListElement>
                  <StyledAnchor>otro3</StyledAnchor>
                </StyledListElement>
                <ProfileDropDown />
              </>
            )}
            {session && (
              <li>
                <button onClick={logoutHandler}>Logout</button>
              </li>
            )}
          </StyledList>
        </StyledNav>
      </div>
      {/* </div> */}
    </>
  );
}
