import React, { useState } from "react";
import StyledHeader from "./StyledHeader";
import ProfileDropDown from "./ProfileDropDown";
import Box from "@mui/material/Box";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import { StyledSectionTitle } from "./StyledHeader";
import LocalFloristIcon from "@material-ui/icons/LocalFlorist";
import SpaIcon from "@material-ui/icons/Spa";
import SportsSoccerIcon from "@material-ui/icons/SportsSoccer";
import StopIcon from "@material-ui/icons/Stop";
import AllInclusiveIcon from "@material-ui/icons/AllInclusive";
import FilterVintageIcon from "@material-ui/icons/FilterVintage";
import GestureIcon from "@material-ui/icons/Gesture";
import SportsHandballIcon from "@material-ui/icons/SportsHandball";
import WavesIcon from "@material-ui/icons/Waves";
import Image from "next/image";
import Head from "next/head";
import style from "./header.module.css";
interface Props {
  handleDrawer?: () => void;
}

export default function Header({ handleDrawer }: Props) {
  const [color, setColor] = useState(false);

  const changeColor = () => {
    if (window.scrollY >= 90) {
      setColor(true);
    } else {
      setColor(false);
    }
  };

  window.addEventListener("scroll", changeColor);
  return (
    <div className={color ? style.headerSolid : style.headerTransparent}>
      <Head>
        <title>Prode Qatar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: "flex" }}>
        <IconButton
          color="inherit"
          aria-label="open drawer"
          edge="start"
          onClick={handleDrawer}
          size="large"
        >
          <MenuIcon />
          <h3>Prode Trinche</h3>
        </IconButton>
        {/* <LocalFloristIcon style={{ color: "#A20D35" }} />
        <SpaIcon style={{ color: "#A20D35" }} />
        <SportsSoccerIcon style={{ color: "#A20D35" }} />
        <StopIcon style={{ color: "#A20D35" }} />
        <AllInclusiveIcon style={{ color: "#A20D35" }} />
        <FilterVintageIcon style={{ color: "#A20D35" }} />
        <GestureIcon style={{ color: "#A20D35" }} />
        <SportsHandballIcon style={{ color: "#A20D35" }} />
        <WavesIcon style={{ color: "#A20D35" }} />
        <LocalFloristIcon style={{ color: "#A20D35" }} />
        <SpaIcon style={{ color: "#A20D35" }} />
        <SportsSoccerIcon style={{ color: "#A20D35" }} />
        <StopIcon style={{ color: "#A20D35" }} />
        <AllInclusiveIcon style={{ color: "#A20D35" }} />
        <FilterVintageIcon style={{ color: "#A20D35" }} />
        <GestureIcon style={{ color: "#A20D35" }} />
        <SportsHandballIcon style={{ color: "#A20D35" }} />
        <WavesIcon style={{ color: "#A20D35" }} />
        <AllInclusiveIcon style={{ color: "#A20D35" }} />
        <LocalFloristIcon style={{ color: "#A20D35" }} />
        <SpaIcon style={{ color: "#A20D35" }} />
        <SportsSoccerIcon style={{ color: "#A20D35" }} />
        <StopIcon style={{ color: "#A20D35" }} />*/}
      </Box>
      {/* <StyledSectionTitle>{section}</StyledSectionTitle> */}
      {/* <Image
        src="/qatar2022.png"
        alt="header Image"
        width={60}
        height={60}
        // layout="fill"
        // objectFit="cover"
        // objectPosition="center"
        // priority={true}
      />*/}
      <div style={{ display: "flex" }}>
        {/* <StopIcon style={{ color: "#A20D35" }} />
        <AllInclusiveIcon style={{ color: "#A20D35" }} />
        <FilterVintageIcon style={{ color: "#A20D35" }} />
        <GestureIcon style={{ color: "#A20D35" }} />
        <LocalFloristIcon style={{ color: "#A20D35" }} />
        <SpaIcon style={{ color: "#A20D35" }} />
        <SportsSoccerIcon style={{ color: "#A20D35" }} />
        <StopIcon style={{ color: "#A20D35" }} />
        <WavesIcon style={{ color: "#A20D35" }} />
        <SportsHandballIcon style={{ color: "#A20D35" }} />
        <GestureIcon style={{ color: "#A20D35" }} />
        <FilterVintageIcon style={{ color: "#A20D35" }} />
        <WavesIcon style={{ color: "#A20D35" }} />
        <SportsHandballIcon style={{ color: "#A20D35" }} />
        <GestureIcon style={{ color: "#A20D35" }} />
        <AllInclusiveIcon style={{ color: "#A20D35" }} />
        <LocalFloristIcon style={{ color: "#A20D35" }} />
        <SpaIcon style={{ color: "#A20D35" }} />
        <SportsSoccerIcon style={{ color: "#A20D35" }} />
        <StopIcon style={{ color: "#A20D35" }} /> */}
        <ProfileDropDown />
      </div>
    </div>
  );
}
