services:
  prode:
    build:
      context: .
    container_name: prode
    ports:
      - 3000:3000
    volumes:
      - .:/prode
      - /prode/node_modules
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - sql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  
  adminer:
    image: adminer:4.8.1
    ports:
        - 8080:8080
    container_name: adminer
    restart: always
    depends_on:
      - db

volumes:
  sql-data:
