export const flags = {
  qatar: "/flags/qatar.png",
  ecuador: "/flags/ecuador.png",
  senegal: "/flags/senegal.png",
  paisesBajos: "/flags/paisesBajos.png",
  inglaterra: "/flags/inglaterra.png",
  iran: "/flags/iran.png",
  gales: "/flags/gales.png",
  argentina: "/flags/argentina.png",
  USA: "/flags/USA.png",
  arabiaSaudita: "/flags/arabiaSaudita.png",
  mexico: "/flags/mexico.png",
  polonia: "/flags/polonia.png",
  francia: "/flags/francia.png",
  australia: "/flags/australia.png",
  dinamarca: "/flags/dinamarca.png",
  tunez: "/flags/tunez.png",
  españa: "/flags/españa.png",
  costaRica: "/flags/costaRica.png",
  alemania: "/flags/alemania.png",
  japon: "/flags/japon.png",
  belgica: "/flags/belgica.png",
  croacia: "/flags/croacia.png",
  canada: "/flags/canada.png",
  marruecos: "/flags/marruecos.png",
  brasil: "/flags/brasil.png",
  serbia: "/flags/serbia.png",
  suiza: "/flags/suiza.png",
  camerun: "/flags/camerun.png",
  portugal: "/flags/portugal.png",
  ghana: "/flags/ghana.png",
  uruguay: "/flags/uruguay.png",
  coreaDelSur: "/flags/coreaDelSur.png",
};

export const getCountry = () => [
  { name: "Qatar", badge: flags.qatar },
  { name: "Ecuador", badge: flags.ecuador },
  { name: "Senegal", badge: flags.senegal },
  { name: "Netherlands", badge: flags.paisesBajos },
  { name: "England", badge: flags.inglaterra },
  { name: "Iran", badge: flags.iran },
  { name: "USA", badge: flags.USA },
  { name: "Wales", badge: flags.gales },
  { name: "Argentina", badge: flags.argentina },
  { name: "Saudi Arabia", badge: flags.arabiaSaudita },
  { name: "Mexico", badge: flags.mexico },
  { name: "Poland", badge: flags.polonia },
  { name: "France", badge: flags.francia },
  { name: "Australia", badge: flags.australia },
  { name: "Denmark", badge: flags.dinamarca },
  { name: "Tunisia", badge: flags.tunez },
  { name: "Spain", badge: flags.españa },
  { name: "Costa Rica", badge: flags.costaRica },
  { name: "Germany", badge: flags.alemania },
  { name: "Japan", badge: flags.japon },
  { name: "Belgium", badge: flags.belgica },
  { name: "Croatia", badge: flags.croacia },
  { name: "Canada", badge: flags.canada },
  { name: "Morocco", badge: flags.marruecos },
  { name: "Brazil", badge: flags.brasil },
  { name: "Serbia", badge: flags.serbia },
  { name: "Switzerland", badge: flags.suiza },
  { name: "Cameroon", badge: flags.camerun },
  { name: "Portugal", badge: flags.portugal },
  { name: "Ghana", badge: flags.ghana },
  { name: "Uruguay", badge: flags.uruguay },
  { name: "South Korea", badge: flags.coreaDelSur },
];
export const getGroups = () => {
  const WorldCupGrups = [
    {
      groupName: "A",
      teams: [
        { name: "Qatar", flag: flags.qatar },
        { name: "Ecuador", flag: flags.ecuador },
        { name: "Senegal", flag: flags.senegal },
        { name: "Netherlands", flag: flags.paisesBajos },
      ],
    },
    {
      groupName: "B",
      teams: [
        { name: "England", flag: flags.inglaterra },
        { name: "Iran", flag: flags.iran },
        { name: "USA", flag: flags.USA },
        { name: "Wales", flag: flags.gales },
      ],
    },
    {
      groupName: "C",
      teams: [
        { name: "Argentina", flag: flags.argentina },
        { name: "Saudi Arabia", flag: flags.arabiaSaudita },
        { name: "Mexico", flag: flags.mexico },
        { name: "Poland", flag: flags.polonia },
      ],
    },
    {
      groupName: "D",
      teams: [
        { name: "France", flag: flags.francia },
        { name: "Australia", flag: flags.australia },
        { name: "Denmark", flag: flags.dinamarca },
        { name: "Tunisia", flag: flags.tunez },
      ],
    },
    {
      groupName: "E",
      teams: [
        { name: "Spain", flag: flags.españa },
        { name: "Costa Rica", flag: flags.costaRica },
        { name: "Germany", flag: flags.alemania },
        { name: "Japan", flag: flags.japon },
      ],
    },
    {
      groupName: "F",
      teams: [
        { name: "Belgium", flag: flags.belgica },
        { name: "Croatia", flag: flags.croacia },
        { name: "Canada", flag: flags.canada },
        { name: "Morocco", flag: flags.marruecos },
      ],
    },
    {
      groupName: "G",
      teams: [
        { name: "Brazil", flag: flags.brasil },
        { name: "Serbia", flag: flags.serbia },
        { name: "Switzerland", flag: flags.suiza },
        { name: "Cameroon", flag: flags.camerun },
      ],
    },
    {
      groupName: "H",
      teams: [
        { name: "Portugal", flag: flags.portugal },
        { name: "Ghana", flag: flags.ghana },
        { name: "Uruguay", flag: flags.uruguay },
        { name: "South Korea", flag: flags.coreaDelSur },
      ],
    },
  ];
  return WorldCupGrups;
};
